version: '3.3'
services:
  result-api:
    build: .
    ports:
      - "9000:80"
    environment:
      - PG_HOST
      - PG_USER
      - PGPASSWORD
      - API_RESULT_HOST
      - API_RESULT_PORT
    networks:
      - backend
      - database


  db:
      image: postgres:10-alpine
      ports:
        - 5433:5432
      environment:
        - POSTGRES_USER
        - POSTGRES_PASSWORD
        - POSTGRES_DB
      volumes:
        - db-data2:/var/lib/postgresql
      networks:
        - database

networks:
  backend:
    external:
      name: backend
  database:

volumes:
  db-data2: