version: '3.3'
services:
  result-api:
    build: .
    ports:
      - "9000:80"
    environment:
      - POSTGRES_HOST
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - API_RESULT_HOST
      - API_RESULT_PORT
      - REDIS_HOST
    volumes:
      - ./:/usr/src


  db:
      build: ./postgres
      ports:
        - "5433:5432"
      environment:
        - POSTGRES_USER
        - POSTGRES_PASSWORD
        - POSTGRES_DB
      volumes:
        - db-data2:/var/lib/postgresql
        - ./postgres/postgresql.conf:/var/lib/postgresql/data/postgresql.conf


volumes:
  db-data2: