version: '3.3'
services:
  result-api:
    build: .
    ports:
      - "9000:80"
    environment:
      - POSTGRES_HOST
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - API_RESULT_HOST
      - API_RESULT_PORT


  db:
      image: postgres:10-alpine
      ports:
        - 5433:5432
      environment:
        - POSTGRES_USER
        - POSTGRES_PASSWORD
        - POSTGRES_DB
      volumes:
        - db-data2:/var/lib/postgresql


volumes:
  db-data2: